apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressclassparams.elbv2.k8s.aws
spec:
  group: elbv2.k8s.aws
  scope: Cluster
  names:
    plural: ingressclassparams
    singular: ingressclassparams
    kind: IngressClassParams
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targetgroupbindings.elbv2.k8s.aws
spec:
  group: elbv2.k8s.aws
  scope: Namespaced
  names:
    plural: targetgroupbindings
    singular: targetgroupbinding
    kind: TargetGroupBinding
