apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app: aws-load-balancer-controller
    spec:
      serviceAccountName: aws-load-balancer-controller
      containers:
        - name: controller
          image: amazon/aws-load-balancer-controller:v2.7.1
          args:
            - --cluster-name=demo-eks
            - --region=us-east-1
          ports:
            - name: webhook-server
              containerPort: 9443
